apiVersion: cilium.io/v2alpha1
kind: CiliumBGPNodeConfig
metadata:
  name: rack0-bgp
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      rack: "rack0"
  bgpInstances:
  - name: "65010"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPNodeConfig
metadata:
  name: rack1-bgp
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      rack: "rack1"
  bgpInstances:
  - name: "65011"
