ipv4NativeRoutingCIDR: "10.0.0.0/8"
kubeProxyReplacement: true
## add-on
externalIPs:
  enabled: true
loadBalancer:
  algorithm: maglev
bgp:
  ## desactive Metal LB
  enabled: false
  announce:
    loadbalancerIP: true
    podCIDR: true
## 

bgpControlPlane:
  ## active GoBGP
  enabled: true
k8s:
  requireIPv4PodCIR: true
ipam:
  mode: kubernetes
