apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-gateway-cert
spec:
  secretName: demo-gateway-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - grpX.randco.eu
